---
- hosts: localhost
  pre_tasks:
    - name: Verify Ansible meets minimum version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.12', '>=')"
        msg: >
          "You must update Ansible to at least 2.12 to use this Ansible Roles."

- name: Install nginx
  hosts: prod_web
  become: yes
  roles:
    - role: nginxinc.nginx
      when: install_nginx | bool

- name: Install PHP
  hosts: prod_web
  become: yes
  roles:
    - role: geerlingguy.php
      when: install_php | bool

- name: LetsEncrypt
  hosts: prod_web
  become: yes
  roles:
    - role: letsencrypt
      when: install_le | bool

- name: Mariadb
  hosts: prod_web
  become: yes
  roles:
    - role: mariadb
      when: install_mariadb | bool

#- name: Install phpMyAdmin
#  hosts: prod_web
#  become: yes
#  roles:
#    - role: phpmyadmin
#      when: install_phpmyadmin | bool
