- name: Install nginx
  hosts: webserver
  become: yes
  roles:
    - { role: nginxinc.nginx }
  vars:
    server_name: "ansible.realtech.dev"
    document_root: /var/www
    app_root: html_demo_site-main
    nginx_path: /etc/nginx 
