- name: Ensure site directories exist
  file:
    path: "{{ nginx_path }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - sites-available
    - sites-enabled

- name: (Common for all OS) copy nginx.conf file to /etc/nginx
  ansible.builtin.template:
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: (Common for all OS) copy example.com.conf.http.j2 to /etc/nginx/sites-available
  ansible.builtin.template:
    src: nginx/sites-available/example.com.conf.http.j2
    dest: /etc/nginx/sites-available/{{ server_name }}.conf

- name: (Common for all OS) Copy nginx general file to /etc/ngnix
  copy:
    src: "nginx/"
    dest: "/etc/nginx/"

- name: Enable Nginx sites
  file:
    path: "{{ nginx_path }}/sites-enabled/{{ server_name }}"
    src: "{{ nginx_path }}/sites-available/{{ server_name }}.conf"
    state: link
    force: yes
  notify: 
     - (Handler) Run NGINX
     - (Handler) Start/reload NGINX



