---
- name: (Debian/Ubuntu) {{ (nginx_setup == 'uninstall') | ternary('Remove', 'Configure') }} NGINX repository
  apt_repository:
    filename: nginx
    repo: "{{ item }}"
    update_cache: true
    mode: 0644
    state: "{{ (nginx_state == 'uninstall') | ternary('absent', 'present') }}"
  loop: "{{ nginx_repository | default(nginx_default_repository_debian) }}"
  when: nginx_manage_repo | bool

- name: (Debian/Ubuntu) {{ (nginx_setup == 'uninstall') | ternary('Unpin', 'Pin') }} NGINX repository
  blockinfile:
    path: /etc/apt/preferences.d/99nginx
    create: true
    block: |
      Package: *
      Pin: origin nginx.org
      Pin: release o=nginx
      Pin-Priority: 900
    mode: 0644
    state: "{{ (nginx_state == 'uninstall') | ternary('absent', 'present') }}"
  when: nginx_repository is not defined

- name: (Debian/Ubuntu) {{ nginx_setup | capitalize }} NGINX
  apt:
    name: "nginx{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
    update_cache: true
    allow_downgrade: true
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX

- name: Copy HTML Website
  include_tasks: common/copy-website.yml

- name: (Debian/Ubuntu) Remove default nginx
  include_tasks: common/remove-default-site.yml

- name: (Debian/Ubuntu) Configure NGINX folder
  include_tasks: common/apply-site-template.yml

