---
# tasks file for mariadb
- name: include distribution dependency variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
- name: Install MariaDB
  include_tasks: "{{ ansible_distribution_file_variety }}-installMariaDB.yml"

- name: Configure MariaDB server
  include_tasks: configure-mariadb.yml

- name: Mysql secure install
  include_tasks: mysql_secure.yml

- name: Initiate Databses users and table
  include_tasks: initiate_database.yml