mariadb_packages:
  - mariadb-server
  - mariadb-common
  - python-openssl
  - python3-mysqldb
repo_software_package:
  - software-properties-common 
  - dirmngr
key_url: "https://mariadb.org/mariadb_release_signing_key.asc"
repo_deb: deb [arch=amd64,arm64,ppc64el] https://mirror.klaus-uwe.me/mariadb/repo/10.4/ubuntu
mariadb_socket: /run/mysqld/mysqld.sock